version: "2"


volumes:
  # chefworkingdir: {}
  content_storage: {}
  build:


services:

  kolibri:
    build:
      dockerfile: Kolibri-prod
      context: ../../dockerfiles
    ports:
      - 9000:80
    expose:
      - "80"
    volumes:
      - ../../build:/build
      - content_storage:/content/storage
    env_file: ../../credentials/prod.env
    environment:
      - KOLIBRI_PEX_PATH=/build/kolibri-0.7.0.pex
      - KOLIBRI_PEX_URL=https://github.com/learningequality/kolibri/releases/download/v0.7.0/kolibri-0.7.0.pex
      - CHANNELS_TO_IMPORT=7765d6aeabc35de790f8bc4532aeb529,dda493eb01d85dd48501bccea5b5e5a8,a31fe7caa1aa59edb2e86b5330b8817f
      # - KOLIBRI_PORT=80
    # command: use default

