version: "2"



volumes:
  # chefworkingdir: {} /data
  #
  kolibri_content: {}
  #
  studio_content: {}
  studio_static: {}
  #
  studiodb_data: {}
  studiodb_backups: {}



services:

  kolibri:
    build:
      dockerfile: Kolibri-prod
      context: ../../dockerfiles
    ports:
      - 9000:80
    volumes:
      - ../../build:/build
      - kolibri_content:/content
    env_file:
      - ../../envs/globals.env
      - ../../envs/prod.env
    environment:
      - KOLIBRI_PEX_PATH=/build/kolibri-0.7.0.pex
      # - KOLIBRI_PEX_URL=https://github.com/learningequality/kolibri/releases/download/v0.7.0/kolibri-0.7.0.pex
      - CHANNELS_TO_IMPORT=7765d6aeabc35de790f8bc4532aeb529,dda493eb01d85dd48501bccea5b5e5a8,a31fe7caa1aa59edb2e86b5330b8817f
      # - KOLIBRI_PORT=80
    # command: use default



  studio:
    build:
      dockerfile: Studio-prod
      context: ../../dockerfiles
    links:
      - studiodb
    ports:
      - 8000:8000
    volumes:
      - studio_content:/content
      - studio_static:/static
    env_file:
      - ../../envs/globals.env
      - ../../envs/prod.env
    environment:
      - DB_CREDENTIALS_HOST=studiodb
      # - DJANGO_SETTINGS_MODULE=contentcuration.dev_settings
      - DJANGO_SETTINGS_MODULE=contentcuration.production_settings
    command: ["gunicorn", "contentcuration.wsgi:application", "--timeout=500", "--error-logfile=/var/log/gunicorn-error.log", "--workers=3", "--bind=0.0.0.0:8000", "--pid=/tmp/contentcuration.pid", "--log-level=debug"]
    # command: ["/bin/sleep", "10000"]
    # /usr/local/bin/gunicorn contentcuration.contentcuration.wsgi:application --timeout=500 --error-logfile=/var/log/gunicorn-error.log --workers=3 --bind=0.0.0.0:8000 --pid=/tmp/contentcuration.pid --log-level=debug


  studiodb:
    image: postgres:9.6
    volumes:
      - studiodb_data:/var/lib/postgresql/data
      - studiodb_backups:/backups
    env_file:
      - ../../envs/globals.env
      - ../../envs/prod.env






